// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna o usu\xE1rio autenticado que est\xE1 chamando o MCP (id e email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-tickets.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tickets_default = defineTool2({
  name: "list_tickets",
  title: "Listar chamados t\xE9cnicos",
  description: "Lista chamados t\xE9cnicos vis\xEDveis ao usu\xE1rio autenticado. Filtros opcionais por status e limite.",
  inputSchema: {
    status: z.enum(["aberto", "em_atendimento", "resolvido", "cancelado"]).optional().describe("Filtro opcional de status do chamado."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de chamados (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb(ctx);
    let q = client.from("tickets").select("id, ticket_code, title, status, priority, created_at, cliente_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-work-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_work_orders_default = defineTool3({
  name: "list_work_orders",
  title: "Listar Ordens de Servi\xE7o da Oficina",
  description: "Lista OS da oficina vis\xEDveis ao usu\xE1rio. Filtros opcionais por status e limite.",
  inputSchema: {
    status: z2.enum(["aguardando", "em_manutencao", "concluido"]).optional().describe("Filtro opcional de status da OS."),
    limit: z2.number().int().min(1).max(50).optional().describe("M\xE1ximo (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb2(ctx);
    let q = client.from("work_orders").select("id, os_code, status, cliente_id, created_at, end_time, total_time_seconds").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { work_orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-parts-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_parts_orders_default = defineTool4({
  name: "list_parts_orders",
  title: "Listar pedidos de pe\xE7as",
  description: "Lista pedidos de pe\xE7as vis\xEDveis ao usu\xE1rio autenticado, ordenados por cria\xE7\xE3o (mais recentes primeiro).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("M\xE1ximo (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const client = sb3(ctx);
    const { data, error } = await client.from("pedidos").select("id, pedido_code, status, cliente_id, urgencia, tipo_envio, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pedidos: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gperaijwlecreqxoygjy";
var mcp_default = defineMcp({
  name: "rumifield-mcp",
  title: "RumiField MCP",
  version: "0.1.0",
  instructions: "Ferramentas do RumiField (gest\xE3o de campo, oficina, chamados e pedidos de pe\xE7as). Use `whoami` para testar conectividade.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_tickets_default, list_work_orders_default, list_parts_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
